name: 'Extract branch name'
description: 'Extracts sanitized branch name and branch id from the provided input'
inputs:
  branch:
    required: false
    description: 'Input to use for branch extraction'
    default: ${{ github.event.ref }}
outputs:
  branch:
    description: 'Sanitized branch name'
    value: ${{ steps.extract_branch.outputs.branch }}
  branch_id:
    description: 'Branch ID'
    value: ${{ steps.extract_branch.outputs.branch_id }}
runs:
  using: 'composite'
  steps:
    - id: extract_branch
      shell: bash
      run: |
        BRANCH_NAME=$(echo ${{ inputs.branch }} | sed -e 's/^refs\/heads\///g' | tr '[:upper:]' '[:lower:]')
        echo "##[set-output name=branch;]$(echo $BRANCH_NAME | sed -e 's/[_\/]/-/g')"
        echo "##[set-output name=branch_id;]$(echo $BRANCH_NAME | sed -e 's/[_\/\-]//g' | cut -c -10)"
