name: 'deploy'
description: 'Deploy built application to Kubernetes'
inputs:
  app_name:
    required: true
    description: ''
  app_hostname:
    required: true
    description: ''
  branch:
    required: true
    description: ''
  docker_registry:
    required: true
    description: ''
  docker_username:
    required: true
    description: ''
  docker_password:
    required: true
    description: ''
  do_access_token:
    required: true
    description: ''
  do_cluster_id:
    required: true
    description: ''
  doppler_token:
    required: false
    description: ''
outputs:
  url:
    description: ''
    value: ${{ jobs.deploy.outputs.url }}
runs:
  using: composite
  steps:
    - name: Checkout (source)
      uses: actions/checkout@v2

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ inputs.do_access_token }}

    - name: Setup Kubernetes
      shell: bash
      env:
        DO_CLUSTER_ID: ${{ inputs.do_cluster_id }}
      run: doctl kubernetes cluster kubeconfig save $DO_CLUSTER_ID

    - name: Install doppler
      env:
        DOPPLER_TOKEN: ${{ inputs.doppler_token }}
      if: "${{ env.DOPPLER_TOKEN != '' }}"
      uses: dopplerhq/cli-action@v1

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: myappartifact
        path: /tmp

    - name: Extract branch name
      id: extract_branch
      shell: bash
      run: |
        BRANCH_NAME=$(echo ${{ inputs.branch }} | sed -e 's/^refs\/heads\///g' | tr '[:upper:]' '[:lower:]')
        echo "##[set-output name=branch;]$(echo $BRANCH_NAME | sed -e 's/[_\/]/-/g')"
        echo "##[set-output name=branch_id;]$(echo $BRANCH_NAME | sed -e 's/[_\/\-]//g' | cut -c -10)"

    - name: Push docker image
      shell: bash
      id: docker_image
      env:
        DOCKER_REGISTRY: ${{ inputs.docker_registry }}
        DOCKER_REPOSITORY: ${{ inputs.app_name }}
        DOCKER_USERNAME: ${{ inputs.docker_username }}
        DOCKER_PASSWORD: ${{ inputs.docker_password }}
      run: |
        IMAGE_NAME=$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$GITHUB_SHA

        docker login $DOCKER_REGISTRY --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        docker load --input /tmp/myappimage.tar
        docker tag ${{ inputs.app_name }} $IMAGE_NAME
        docker push $IMAGE_NAME

        echo "##[set-output name=name;]$(echo $IMAGE_NAME)"

    - name: Deploy to kubernetes
      shell: bash
      id: deploy
      # kube configurations can use following environment variables along with the default ones provided by GitHub action
      # https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
      env:
        DOPPLER_PROJECT: ${{ inputs.app_name }}
        DOPPLER_CONFIG: preview
        DOPPLER_TOKEN: ${{ inputs.doppler_token }}
        KUBE_NS: ${{ inputs.app_name }}-preview
        KUBE_APP: ${{ inputs.app_name }}-preview-${{ steps.extract_branch.outputs.branch_id }}
        KUBE_ENV: preview
        KUBE_DEPLOYMENT_IMAGE: ${{ steps.docker_image.outputs.name }}
        KUBE_INGRESS_HOSTNAME: ${{ steps.extract_branch.outputs.branch_id }}.${{ inputs.app_hostname }}
      run: |
        source platform/src/scripts/kube/deploy.sh
        echo "##[set-output name=url;]$(echo https://$KUBE_INGRESS_HOSTNAME)"
