name: 'lint'
description: 'Run lint checks'
runs:
  using: composite
  steps:
    - name: Run linting
      shell: bash
      env:
        DOCKER_IMAGE: ${{ inputs.tag }}
      run: |
        npm run lint
