name: clean

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      app_env:
        required: true
        type: string
      branch:
        required: true
        type: string
      platform_version:
        required: false
        type: string
        description: 'Branch from which platform will be checked out to use actions'
        default: 'v2.1'
    secrets:
      do_access_token:
        required: true
      do_cluster_id:
        required: true

jobs:
  clean:
    runs-on: ubuntu-latest
    # make sure to run a single deployment job against the provided branch
    # following will prioritize the most recent invocation and cancel existing ones if any were found
    # important - make sure deploy and clean are using same group
    concurrency:
      group: default-${{ inputs.app_env }}-${{ inputs.branch }}
      cancel-in-progress: true
    steps:
      - name: Checkout (source)
        uses: actions/checkout@v2

      - name: Checkout (action)
        uses: actions/checkout@v2
        with:
          repository: jalantechnologies/platform-github
          path: platform
          ref: ${{ inputs.platform_version }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.do_access_token }}

      - name: Setup Kubernetes
        env:
          DO_CLUSTER_ID: ${{ secrets.do_cluster_id }}
        run: doctl kubernetes cluster kubeconfig save $DO_CLUSTER_ID

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: |
          BRANCH_HASH=$(sha1sum < <(printf '%s' ${{ inputs.branch }}) | cut -c -15)
          BRANCH_NAME=$(echo ${{ inputs.branch }} | sed -e 's/^refs\/heads\///g')

          echo "##[set-output name=branch_hash;]$(echo $BRANCH_HASH)"
          echo "##[set-output name=branch;]$(echo $BRANCH_NAME)"

      - name: Clean up
        env:
          KUBE_NS: ${{ inputs.app_name }}-${{ inputs.app_env }}
          KUBE_APP: ${{ inputs.app_name }}-${{ inputs.app_env }}-${{ steps.extract_branch.outputs.branch_hash }}
          KUBE_ENV: ${{ inputs.app_env }}
        run: |
          source platform/src/scripts/kube/clean.sh
