name: production

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      app_hostname:
        required: true
        type: string
      branch:
        required: true
        type: string
    secrets:
      docker_registry:
        required: true
      docker_username:
        required: true
      docker_password:
        required: true
      doppler_token:
        required: true
      do_access_token:
        required: true
      do_cluster_id:
        required: true
      sonar_token:
        required: false
      sonar_host_url:
        required: false

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: sonarqube-scan-branch
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.sonar_token }}
          SONAR_HOST_URL: ${{ secrets.sonar_host_url }}
        if: "${{ env.SONAR_TOKEN != '' }}"
        with:
          args: >
            -Dsonar.branch.name=${{ inputs.branch }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docker image
        shell: bash
        run: |
          docker build --platform linux/amd64 -t ${{ inputs.app_name }} .
          docker save ${{ inputs.app_name }} > /tmp/myappimage.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: myappartifact
          path: /tmp/myappimage.tar

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: myappartifact
          path: /tmp

      - name: Run linting
        shell: bash
        run: |
          docker load --input /tmp/myappimage.tar
          docker run -t ${{ inputs.app_name }} npm run lint

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: myappartifact
          path: /tmp

      - name: Run tests
        shell: bash
        run: |
          docker load --input /tmp/myappimage.tar
          docker-compose -f docker-compose.test.yml up --exit-code-from app

  deploy:
    needs: [ 'build', 'test' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.do_access_token }}

      - name: Setup Kubernetes
        shell: bash
        env:
          DO_CLUSTER_ID: ${{ secrets.do_cluster_id }}
        run: doctl kubernetes cluster kubeconfig save $DO_CLUSTER_ID

      - name: Install doppler
        uses: dopplerhq/cli-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: myappartifact
          path: /tmp

      - name: Push docker image
        shell: bash
        id: docker_image
        env:
          DOCKER_REGISTRY: ${{ secrets.docker_registry }}
          DOCKER_REPOSITORY: ${{ inputs.app_name }}
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
          IMAGE_TAG: production
        run: |
          IMAGE_NAME=$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG
          
          docker login $DOCKER_REGISTRY --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          docker load --input /tmp/myappimage.tar
          docker tag ${{ inputs.app_name }} $IMAGE_NAME
          docker push $IMAGE_NAME
          
          echo "##[set-output name=name;]$(echo $IMAGE_NAME)"

      - name: Deploy to kubernetes
        shell: bash
        id: deploy
        env:
          DOPPLER_PROJECT: ${{ inputs.app_name }}
          DOPPLER_CONFIG: production
          DOPPLER_TOKEN: ${{ secrets.doppler_token }}
          KUBE_NS: ${{ inputs.app_name }}-production
          KUBE_APP: ${{ inputs.app_name }}-production
          KUBE_ENV: production
          KUBE_DEPLOYMENT_IMAGE: ${{ steps.docker_image.outputs.name }}
          KUBE_INGRESS_HOSTNAME: ${{ inputs.app_hostname }}
        run: |
          source deploy/kube.sh
          echo "##[set-output name=url;]$(echo https://$KUBE_INGRESS_HOSTNAME)"
