name: production

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      app_hostname:
        required: true
        type: string
      branch:
        required: true
        type: string
      steps:
        required: false
        type: string
    secrets:
      docker_registry:
        required: true
      docker_username:
        required: true
      docker_password:
        required: true
      do_access_token:
        required: true
      do_cluster_id:
        required: true
      doppler_token:
        required: false
      sonar_token:
        required: false
      sonar_host_url:
        required: false

jobs:
  analyze:
    runs-on: ubuntu-latest
    if: inputs.steps == '' || contains(join(inputs.steps), 'analyze')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: sonarqube-scan-branch
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.sonar_token }}
          SONAR_HOST_URL: ${{ secrets.sonar_host_url }}
        if: "${{ env.SONAR_TOKEN != '' }}"
        with:
          args: >
            -Dsonar.branch.name=${{ inputs.branch }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (action)
        uses: actions/checkout@v2
        with:
          repository: jalantechnologies/platform-github
          path: platform

      - name: Build application
        uses: ./platform/.github/actions/build
        with:
          tag: ${{ inputs.app_name }}

  lint:
    runs-on: ubuntu-latest
    needs: build
    if: inputs.steps == '' || contains(join(inputs.steps), 'lint')
    steps:
      - name: Checkout (action)
        uses: actions/checkout@v2
        with:
          repository: jalantechnologies/platform-github
          path: platform

      - name: Runs lint checks
        uses: ./platform/.github/actions/lint
        with:
          tag: ${{ inputs.app_name }}

  test:
    runs-on: ubuntu-latest
    needs: build
    if: inputs.steps == '' || contains(join(inputs.steps), 'test')
    steps:
      - name: Checkout (action)
        uses: actions/checkout@v2
        with:
          repository: jalantechnologies/platform-github
          path: platform

      - name: Run automated test cases
        uses: ./platform/.github/actions/test

  deploy:
    needs: [ 'build', 'test' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (source)
        uses: actions/checkout@v2

      - name: Checkout (action)
        uses: actions/checkout@v2
        with:
          repository: jalantechnologies/platform-github
          path: platform

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.do_access_token }}

      - name: Setup Kubernetes
        shell: bash
        env:
          DO_CLUSTER_ID: ${{ secrets.do_cluster_id }}
        run: doctl kubernetes cluster kubeconfig save $DO_CLUSTER_ID

      - name: Install doppler
        env:
          DOPPLER_TOKEN: ${{ secrets.doppler_token }}
        if: "${{ env.DOPPLER_TOKEN != '' }}"
        uses: dopplerhq/cli-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: myappartifact
          path: /tmp

      - name: Push docker image
        shell: bash
        id: docker_image
        env:
          DOCKER_REGISTRY: ${{ secrets.docker_registry }}
          DOCKER_REPOSITORY: ${{ inputs.app_name }}
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
        run: |
          IMAGE_NAME=$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$GITHUB_SHA

          docker login $DOCKER_REGISTRY --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          docker load --input /tmp/myappimage.tar
          docker tag ${{ inputs.app_name }} $IMAGE_NAME
          docker push $IMAGE_NAME

          echo "##[set-output name=name;]$(echo $IMAGE_NAME)"

      - name: Deploy to kubernetes
        shell: bash
        id: deploy
        # kube configurations can use following environment variables along with the default ones provided by GitHub action
        # https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
        env:
          DOPPLER_PROJECT: ${{ inputs.app_name }}
          DOPPLER_CONFIG: production
          DOPPLER_TOKEN: ${{ secrets.doppler_token }}
          KUBE_NS: ${{ inputs.app_name }}-production
          KUBE_APP: ${{ inputs.app_name }}-production
          KUBE_ENV: production
          KUBE_DEPLOYMENT_IMAGE: ${{ steps.docker_image.outputs.name }}
          KUBE_INGRESS_HOSTNAME: ${{ inputs.app_hostname }}
        run: |
          source platform/src/scripts/kube/deploy.sh
          echo "##[set-output name=url;]$(echo https://$KUBE_INGRESS_HOSTNAME)"

  clean:
    runs-on: ubuntu-latest
    if: ${{ always() && !cancelled() }}
    # list all jobs after which clean up should be performed
    needs: [ 'lint', 'test', 'deploy' ]
    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: myappartifact
          failOnError: false
