name: staging

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      branch:
        required: true
        type: string
      hostname:
        required: true
        type: string
      docker_registry:
        required: true
        type: string
      docker_username:
        required: true
        type: string
      docker_password:
        required: true
        type: string
      doppler_token:
        required: true
        type: string
      do_access_token:
        required: true
        type: string
      do_cluster_id:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build application
        uses: ./.github/actions/build
        with:
          image_tag: ${{ inputs.app }}

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run linting check
        uses: ./.github/actions/lint
        with:
          image_tag: ${{ inputs.app }}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run automated test cases
        uses: ./.github/actions/test

  preview:
    runs-on: ubuntu-latest
    needs: build
    # make sure to run a single job against the provided branch
    # following will prioritize the most recent invocation and cancel existing ones if any were found
    # important - make sure preview and clean are using same group
    concurrency:
      group: preview-${{ inputs.branch }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/deploy
        id: deploy
        with:
          app_name: ${{ inputs.app }}
          app_namespace: ${{ inputs.app }}-preview
          app_environment: preview
          app_hostname: ${{ inputs.hostname }}
          branch: ${{ inputs.branch }}
          docker_registry: ${{ inputs.docker_registry }}
          docker_repository: ${{ inputs.app }}
          docker_username: ${{ inputs.docker_username }}
          docker_password: ${{ inputs.docker_password }}
          doppler_token: ${{ inputs.doppler_token }}
          do_access_token: ${{ inputs.do_access_token }}
          do_cluster_id: ${{ inputs.do_cluster_id }}

      - name: Extract pull request number
        id: extract_pr_number
        uses: jwalton/gh-find-current-pr@v1

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          hide_and_recreate: true
          hide_classify: 'OUTDATED'
          number: ${{ steps.extract_pr_number.outputs.number }}
          message: |
            Preview is available at - ${{ steps.deploy.outputs.url }}
